# Generated by Django 4.2.2 on 2023-08-07 03:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0007_alter_person_gender_alter_person_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('name_application', models.CharField(max_length=200)),
                ('description_application', models.CharField(max_length=200)),
                ('url_back_application', models.CharField(max_length=1000)),
                ('url_front_application', models.CharField(max_length=1000)),
                ('technologies_application', models.CharField(max_length=1000)),
                ('person_fk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
