# Generated by Django 4.2.2 on 2023-06-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterModelOptions(
            name='parameterdetail',
            options={'verbose_name': 'Parameter Detail', 'verbose_name_plural': 'Parameters Details'},
        ),
        migrations.AlterModelOptions(
            name='typeparameter',
            options={'verbose_name': 'Type parameter', 'verbose_name_plural': 'Types parameters'},
        ),
    ]
