# Generated by Django 4.2.2 on 2023-06-30 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_alter_parameter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeparameter',
            name='Status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='typeparameter',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='typeparameter',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
