# Generated by Django 4.2.2 on 2023-06-30 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_typeparameter_status_typeparameter_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeparameter',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='parameter',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='parameter',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='parameterdetail',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='parameterdetail',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdetail',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='typeparameter',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
