# Generated by Django 4.2.2 on 2023-08-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('parameter', '0004_rename_status_typeparameter_status_parameter_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='application_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.application', verbose_name='Type parameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type_parameter_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.typeparameter', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='parameterdetail',
            name='parameter_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameter.parameter', verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='parameterdetail',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='typeparameter',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
    ]
