# Generated by Django 4.2.2 on 2023-06-30 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(default=uuid.UUID('fe8a6d08-175e-11ee-b526-a675ca0253ef'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.CharField(default=uuid.UUID('fe8a6272-175e-11ee-b526-a675ca0253ef'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='code',
            field=models.CharField(default=uuid.UUID('fe8a6876-175e-11ee-b526-a675ca0253ef'), max_length=100),
        ),
    ]
