# Generated by Django 4.2.2 on 2023-06-30 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_code_alter_typedocument_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(default=uuid.UUID('23b09b90-e972-4d07-9802-846a21657b59'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.CharField(default=uuid.UUID('31b6dd40-a063-4bc3-ada3-8e239bf0b004'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='code',
            field=models.CharField(default=uuid.UUID('e5d0cbd4-4310-43aa-b9a7-4edb4262eafe'), max_length=100),
        ),
    ]
