# Generated by Django 4.2.2 on 2023-06-30 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_code_alter_typedocument_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(default=uuid.UUID('91f717f9-3094-4c81-a9ec-0a816111c536'), max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.CharField(default=uuid.UUID('eb7f2971-d2c4-4ef6-ab96-c410b6f2e3e8'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='code',
            field=models.CharField(default=uuid.UUID('cf739ff4-4365-4c46-9edc-bd4c9bcf2657'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
    ]
