# Generated by Django 4.2.2 on 2023-06-30 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_person_code_alter_person_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.CharField(default=uuid.UUID('ec74c6eb-51b2-4595-bf7c-abdc78d72987'), max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.CharField(default=uuid.UUID('d714a4b5-9002-4a8a-912c-51af55d14833'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='code',
            field=models.CharField(default=uuid.UUID('9ea32a64-17c9-43a2-8507-b9568808e163'), max_length=100),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
