# Generated by Django 4.2.2 on 2023-06-30 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_code_alter_person_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='typeperson',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
