# Generated by Django 4.2.2 on 2023-08-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_status_typedocument_status_typeperson_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='F', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='typeperson',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
    ]
